Further improvements to error handling

diff --git a/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml b/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
--- a/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
+++ b/03 - Lab 3 - Backup and Restore/backup/zeebe-backup-job.yaml
@@ -44,7 +44,7 @@ spec:
               echo "Backup $BACKUP_TIME_ID failed or in an unknown state."
               fail_count=$((fail_count+1))
               if [ $fail_count -ge 3 ]; then
-                echo "Failed 3 times, exiting."
+                echo "ERROR: Failed 3 times, exiting." >&2
                 exit 1
               else
                 echo "Retrying, attempt $fail_count of 3."
diff --git a/03 - Lab 3 - Backup and Restore/backup/zeebe-export-resume.yaml b/03 - Lab 3 - Backup and Restore/backup/zeebe-export-resume.yaml
--- a/03 - Lab 3 - Backup and Restore/backup/zeebe-export-resume.yaml
+++ b/03 - Lab 3 - Backup and Restore/backup/zeebe-export-resume.yaml
@@ -15,5 +15,11 @@ spec:
           curl --fail -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/resume" \
             -H 'Content-Type: application/json' \
             -d '{}'
-          echo "Exporting resumed on camunda-zeebe-gateway."
+          success=$?
+          if [ "$success" ]; then
+            echo "Exporting resumed on camunda-zeebe-gateway."
+          else
+            echo "ERROR: Could not resume exporting on camunda-zeebe-gateway"  >&2
+            exit 1
+          fi
       restartPolicy: Never
diff --git a/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml b/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
--- a/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
+++ b/03 - Lab 3 - Backup and Restore/restore/es-snapshot-restore-job.yaml
@@ -44,7 +44,8 @@ spec:
                 curl --fail --request POST "$elasticsearch_endpoint/_snapshot/$repository/$snapshot/_restore?wait_for_completion=true"
                 echo "Restore completed for snapshot: $snapshot in repository: $repository"
               else
-                echo "No matching snapshots found in repository $repository."
+                echo "ERROR: No matching snapshots found in repository $repository." >&2
+                exit 1
               fi
             done
           done
diff --git a/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-2.yaml b/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-2.yaml
--- a/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-2.yaml
+++ b/03 - Lab 3 - Backup and Restore/restore/zeebe-restore-job-2.yaml
@@ -11,11 +11,15 @@ spec:
         command: ["/bin/bash", "-c"]
         args:
         - |
-          ls -laR /usr/local/zeebe/data
+          ls -lAR /usr/local/zeebe/data
           rm -rf /usr/local/zeebe/data/{*,.*}
           echo "Starting restoration process..."
-          ls -laR /usr/local/zeebe/data
-          /usr/local/zeebe/bin/restore --backupId=${ZEEBE_RESTORE_FROM_BACKUP_ID} && echo "Restoration complete."
+          if [-z "$(ls -A /usr/local/zeebe/data)"]; then
+            /usr/local/zeebe/bin/restore --backupId=${ZEEBE_RESTORE_FROM_BACKUP_ID} && echo "Restoration complete."
+          else
+            echo "ERROR: Could not delete zeebe data" >&2
+            exit 1
+          fi
         env:
         - name: ZEEBE_RESTORE_FROM_BACKUP_ID
           valueFrom:
